name: 'Teleport Application Proxy'
description: 'Opens a local HTTP proxy server in the background of your workflow that can be used to access HTTP apps available in Teleport.'
inputs:
  listen:
    description: 'Specify a listener URI for the local tunnel, e.g. tcp://localhost:1234'
    required: true
  timeout-ms:
    description: 'The maximum amount of time to wait in milliseconds for the tunnel to become ready. Set to 0 to skip waiting.'
    required: false
    default: '30000'
  diag-port:
    description: 'Specify an alternative port for the diagnostics service.'
    required: false
    default: '57263'

runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'

# Extend functionality provided by gamma; fields whitelisted to avoid
# overwriting `runs`.
extend:
  - from: '@/common/action.yml'
    include:
      - field: inputs
      - field: branding
      - field: author
