author: Gravitational, Inc.
inputs:
  token:
    description: 'Specify the Teleport token to use to join.'
    required: true
  proxy:
    description: 'Specify the address of your Teleport Proxy.'
    required: true
  certificate-ttl:
    description: 'Specify the length that the generated credentials should be valid for. Defaults to "1h"'
    required: false
  anonymous-telemetry:
    description: 'Enables anonymous telemetry. See https://goteleport.com/docs/machine-id/reference/telemetry/ for more information.'
    required: false
  ca-pins:
    description: 'Specifies one or more trusted CAs to initially validate the identity of the Auth Server when connecting directly to it. This is not required for Teleport Cloud or when connecting via a Teleport Proxy'
    required: false
branding:
  icon: terminal
  color: 'purple'
runs:
  using: 'node16'
  main: 'dist/index.js'
