name: 'Teleport Setup'
description: 'Installs `teleport`, `tsh`, `tbot` and `tctl`.'
inputs:
  version:
    required: true
    description: 'Specify the Teleport version without the preceding "v"'
  enterprise:
    required: false
    default: 'false'
    description: 'Specify whether to use the enterprise binaries.'
extend:
  - from: '@/common/action.yml'
    include:
      - field: runs
      - field: author
      - field: branding
