name: 'Teleport Database Tunnel'
description: 'Opens a local tunnel in the background of your workflow to a database protected by Teleport.'
inputs:
  listen:
    description: 'Specify a listener URI for the local tunnel, e.g. tcp://localhost:1234'
    required: true
  timeout-ms:
    description: 'The maximum amount of time to wait in milliseconds for the tunnel to become ready. Set to 0 to skip waiting.'
    required: false
    default: '30000'
  diag-port:
    description: 'Specify an alternative port for the diagnostics service.'
    required: false
    default: '57263'

  service:
    description: 'Specify the name of the Teleport database, generally the resource name in Teleport.'
    required: true
  database:
    description: 'Specify the name of the database within the Teleport database service to which a connection should be opened'
  username:
    description: 'Specify the name of the database user that should access the database.'

runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'

# Extend functionality provided by gamma; fields whitelisted to avoid
# overwriting `runs`.
extend:
  - from: '@/common/action.yml'
    include:
      - field: inputs
      - field: branding
      - field: author
