name: Deploy actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Make sure you set this, as Gamma needs the Git history

      - uses: actions/setup-node@v3

      - uses: gravitational/setup-gamma@v1

      - run: yarn # Install your dependencies as normal

      - name: Deploy actions
        run: gamma deploy
        env:
          GITHUB_APP_INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}
          GITHUB_APP_ID: ${{ secrets.APP_ID }}
          GITHUB_APP_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
